@truckPRO_api_HostAddress = https://localhost:7010

GET {{truckPRO_api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{truckPRO_api_HostAddress}}/Login
Content-Type: application/json

{
   "email": "fort@example.com",
   "password": "SecurePassword123!"
}


###
POST {{truckPRO_api_HostAddress}}/SignUp
Content-Type: application/json

{
  
  "FirstName": "John",
  "LastName": "Doe",
  "Email": "john.doe@example.com",
  "Password": "SecurePassword123!",
  "Role": "Driver",
  "CompanyId": 1


}

###
GET {{truckPRO_api_HostAddress}}/test/driver-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwiZXhwIjoxNzI2MDMwMjM5LCJpc3MiOiJKd3RJc3N1ZXIiLCJhdWQiOiJKd3RBdWRpZW5jZSJ9.NDtjypEZ4VdpSLQydtyzyH6hHW60fVzwklzuJDMC2GA
Content-Type: application/json
{

}

###


###
GET {{truckPRO_api_HostAddress}}/test/token-claims
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwiZXhwIjoxNzI2MDI5NzgxLCJpc3MiOiJKd3RJc3N1ZXIiLCJhdWQiOiJKd3RBdWRpZW5jZSJ9.gzmciV0ZGdkGeVPIYmylgnmv08nasxWrDY1cwce4HvA
Content-Type: application/json
{

}

###


###
POST {{truckPRO_api_HostAddress}}/CreateOnDutyLog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwidXNlcklkIjoiNCIsImV4cCI6MTcyNjA5NDM3NCwiaXNzIjoiSnd0SXNzdWVyIiwiYXVkIjoiSnd0QXVkaWVuY2UifQ.wUZVIA98cLV48ONz6V3fjulDwm1KCqfZ5cHxvcY4lqM
Content-Type: application/json
{

}

###

###
POST {{truckPRO_api_HostAddress}}/createDrivingLog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwiZXhwIjoxNzI2MDg4MTk5LCJpc3MiOiJKd3RJc3N1ZXIiLCJhdWQiOiJKd3RBdWRpZW5jZSJ9.24mk1egnBVKsHEv7jBIvZtYhHaZDBATt1R_QDJK-yfg 
Content-Type: application/json
{

}

###
