@truckPRO_api_HostAddress = https://localhost:7010

GET {{truckPRO_api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{truckPRO_api_HostAddress}}/Login
Content-Type: application/json

{
   "email": "manager@example.com",
   "password": "SecurePassword123!"
}


###
POST {{truckPRO_api_HostAddress}}/SignUp
Content-Type: application/json

{
  
  "FirstName": "Manager",
  "LastName": "DManageroe",
  "Email": "manager@example.com",
  "Password": "SecurePassword123!",
  "Phone": "3128383865",
  "ConfirmPassword": "SecurePassword123!",
  "Role": "Manager",
  "CompanyId": 1


}

###
GET {{truckPRO_api_HostAddress}}/test/driver-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwiZXhwIjoxNzI2MDMwMjM5LCJpc3MiOiJKd3RJc3N1ZXIiLCJhdWQiOiJKd3RBdWRpZW5jZSJ9.NDtjypEZ4VdpSLQydtyzyH6hHW60fVzwklzuJDMC2GA
Content-Type: application/json
{

}

###


###
GET {{truckPRO_api_HostAddress}}/test/token-claims
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwiZXhwIjoxNzI2MDI5NzgxLCJpc3MiOiJKd3RJc3N1ZXIiLCJhdWQiOiJKd3RBdWRpZW5jZSJ9.gzmciV0ZGdkGeVPIYmylgnmv08nasxWrDY1cwce4HvA
Content-Type: application/json
{

}

###


###
POST {{truckPRO_api_HostAddress}}/CreateOnDutyLog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwidXNlcklkIjoiNCIsImV4cCI6MTcyNjE4NDA0MSwiaXNzIjoiSnd0SXNzdWVyIiwiYXVkIjoiSnd0QXVkaWVuY2UifQ.M-xqondXicPRZcdXtF4izhdjI0ELlbTmMq23YwkXra0
Content-Type: application/json
{

}

###

###
POST {{truckPRO_api_HostAddress}}/createDrivingLog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwidXNlcklkIjoiNCIsImV4cCI6MTcyNjE3OTY4MCwiaXNzIjoiSnd0SXNzdWVyIiwiYXVkIjoiSnd0QXVkaWVuY2UifQ.vAKZz9av5lMsJmL1E105-5rQ78r_n53bEs8UVo-_UGo
Content-Type: application/json
{

}

###

POST {{truckPRO_api_HostAddress}}/createOffDutyLog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwidXNlcklkIjoiNCIsImV4cCI6MTcyNjExNDUwNSwiaXNzIjoiSnd0SXNzdWVyIiwiYXVkIjoiSnd0QXVkaWVuY2UifQ.kO4S9c-eWNdQ9P4pg_Zfo9kHzkOmhUKn0Ap7jncoJ38
Content-Type: application/json
{

}

###


POST {{truckPRO_api_HostAddress}}/createOffDutyLog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwidXNlcklkIjoiNCIsImV4cCI6MTcyNjE3OTY4MCwiaXNzIjoiSnd0SXNzdWVyIiwiYXVkIjoiSnd0QXVkaWVuY2UifQ.vAKZz9av5lMsJmL1E105-5rQ78r_n53bEs8UVo-_UGo
Content-Type: application/json
{

}


###

POST {{truckPRO_api_HostAddress}}/stopOffDutyLog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwidXNlcklkIjoiNCIsImV4cCI6MTcyNjE3OTY4MCwiaXNzIjoiSnd0SXNzdWVyIiwiYXVkIjoiSnd0QXVkaWVuY2UifQ.vAKZz9av5lMsJmL1E105-5rQ78r_n53bEs8UVo-_UGo
Content-Type: application/json
{

}
### 

GET {{truckPRO_api_HostAddress}}/AllDriversByCompany
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYW5hZ2VyQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiTWFuYWdlciIsInVzZXJJZCI6IjciLCJjb21wYW55SWQiOiIxIiwiZXhwIjoxNzI2MTg5MjE2LCJpc3MiOiJKd3RJc3N1ZXIiLCJhdWQiOiJKd3RBdWRpZW5jZSJ9.WXqZX_qbU_tAZberQPCwApXj9qyccyExUSjMJLJyq9Y
Content-Type: application/json
{

}
### 

