@truckPRO_api_HostAddress = https://localhost:7010

GET {{truckPRO_api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{truckPRO_api_HostAddress}}/Login
Content-Type: application/json

{
   "email": "admin@example.com",
   "password": "SecurePassword123!"
}


###
POST {{truckPRO_api_HostAddress}}/SignUp
Content-Type: application/json

{
  
  "FirstName": "Taras",
  "LastName": "Stefan",
  "Email": "Stefan@example.com",
  "Password": "SecurePassword123!",
  "Phone": "3128383865",
  "ConfirmPassword": "SecurePassword123!",
  "Role": 0
}

###
GET {{truckPRO_api_HostAddress}}/test/driver-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwiZXhwIjoxNzI2MDMwMjM5LCJpc3MiOiJKd3RJc3N1ZXIiLCJhdWQiOiJKd3RBdWRpZW5jZSJ9.NDtjypEZ4VdpSLQydtyzyH6hHW60fVzwklzuJDMC2GA
Content-Type: application/json
{

}

###


###
GET {{truckPRO_api_HostAddress}}/test/token-claims
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwiZXhwIjoxNzI2MDI5NzgxLCJpc3MiOiJKd3RJc3N1ZXIiLCJhdWQiOiJKd3RBdWRpZW5jZSJ9.gzmciV0ZGdkGeVPIYmylgnmv08nasxWrDY1cwce4HvA
Content-Type: application/json
{

}

###


###
POST {{truckPRO_api_HostAddress}}/createOnDutyLog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwidXNlcklkIjoiMTUiLCJjb21wYW55SWQiOiIiLCJleHAiOjE3MjYyNjYyNjQsImlzcyI6Ikp3dElzc3VlciIsImF1ZCI6Ikp3dEF1ZGllbmNlIn0.ScwMlrK_fvUQoG-AbM0rD95FgNiuqTV0ob8UCqC6uUQ
Content-Type: application/json
{

}

###

###
POST {{truckPRO_api_HostAddress}}/createDrivingLog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwidXNlcklkIjoiMTUiLCJjb21wYW55SWQiOiIiLCJleHAiOjE3MjYyNjYyNjQsImlzcyI6Ikp3dElzc3VlciIsImF1ZCI6Ikp3dEF1ZGllbmNlIn0.ScwMlrK_fvUQoG-AbM0rD95FgNiuqTV0ob8UCqC6uUQContent-Type: application/json
{


}

###

POST {{truckPRO_api_HostAddress}}/createOffDutyLog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwidXNlcklkIjoiNCIsImV4cCI6MTcyNjExNDUwNSwiaXNzIjoiSnd0SXNzdWVyIiwiYXVkIjoiSnd0QXVkaWVuY2UifQ.kO4S9c-eWNdQ9P4pg_Zfo9kHzkOmhUKn0Ap7jncoJ38
Content-Type: application/json
{

}

###


POST {{truckPRO_api_HostAddress}}/createOffDutyLog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwidXNlcklkIjoiNCIsImV4cCI6MTcyNjE3OTY4MCwiaXNzIjoiSnd0SXNzdWVyIiwiYXVkIjoiSnd0QXVkaWVuY2UifQ.vAKZz9av5lMsJmL1E105-5rQ78r_n53bEs8UVo-_UGo
Content-Type: application/json
{

}


###

POST {{truckPRO_api_HostAddress}}/stopOffDutyLog
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmb3J0QGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRHJpdmVyIiwidXNlcklkIjoiNCIsImV4cCI6MTcyNjE3OTY4MCwiaXNzIjoiSnd0SXNzdWVyIiwiYXVkIjoiSnd0QXVkaWVuY2UifQ.vAKZz9av5lMsJmL1E105-5rQ78r_n53bEs8UVo-_UGo
Content-Type: application/json
{

}
### 

GET {{truckPRO_api_HostAddress}}/allDriversByCompany
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwidXNlcklkIjoiMTUiLCJjb21wYW55SWQiOiIiLCJleHAiOjE3MjYyNjYyNjQsImlzcyI6Ikp3dElzc3VlciIsImF1ZCI6Ikp3dEF1ZGllbmNlIn0.ScwMlrK_fvUQoG-AbM0rD95FgNiuqTV0ob8UCqC6uUQ
Content-Type: application/json
{

}
### 


GET {{truckPRO_api_HostAddress}}/allLogsByDriver?driverId=4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYW5hZ2VyQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiTWFuYWdlciIsInVzZXJJZCI6IjciLCJjb21wYW55SWQiOiIxIiwiZXhwIjoxNzI2MjU0ODMwLCJpc3MiOiJKd3RJc3N1ZXIiLCJhdWQiOiJKd3RBdWRpZW5jZSJ9.r_1bohD-Mb3mEWCSqbHgV--kFx8-HRONs4yPT-wgQ1o 
Content-Type: application/json
{

}
### 

POST {{truckPRO_api_HostAddress}}/signUpManager
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwidXNlcklkIjoiMTUiLCJjb21wYW55SWQiOiIiLCJleHAiOjE3MjYyNjYyNjQsImlzcyI6Ikp3dElzc3VlciIsImF1ZCI6Ikp3dEF1ZGllbmNlIn0.ScwMlrK_fvUQoG-AbM0rD95FgNiuqTV0ob8UCqC6uUQ
Content-Type: application/json
{
    
  "FirstName": "Taras",
  "LastName": "Stefan",
  "Email": "Stefan@example.com",
  "Password": "SecurePassword123!",
  "Phone": "3128383865",
  "ConfirmPassword": "SecurePassword123!",
  "Role": 1,
  "CompanyId": 1
  
}
###

POST {{truckPRO_api_HostAddress}}/verifyEmail?emailToken=677214
Content-Type: application/json
{
  "emailToken": "384601"
  
}


###

Get {{truckPRO_api_HostAddress}}/adm/GetAllDrivers
Authorization: Bearer 
Content-Type: application/json
{
 
  
}
###

Get {{truckPRO_api_HostAddress}}/adm/getDriversByCompanyId?companyId=1
Authorization: Bearer 
Content-Type: application/json
{
  
  
}



