name: Deploy to Windows VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SSH Commands on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: |
            echo 'Starting deployment on Windows VPS...'
            cmd /c "C:\Users\Administrator\Documents\truckProRepo\truckPRO_api\deploy.bat"
