name: Deploy to VPS

on:
  push:
    branches:
      - master # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy publish folder to VPS
      run: |
        ssh Administrator@174.138.184.240 "C:\\Users\\Administrator\\Documents\\truckProRepo\\truckPRO_api\\deploy.bat" 
