name: Deploy to VPS

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy publish folder to VPS
      shell: pwsh  
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  
      run: |
        # Write the SSH key to a file
        echo $env:SSH_PRIVATE_KEY > key
        # Set permissions for the SSH key file (optional but recommended for security)
        icacls key /inheritance:r /grant:r "$($env:USERNAME):(R)"
        # Use SSH to execute the deploy script on the VPS
        ssh -i key Administrator@174.138.184.240 "C:\\Users\\Administrator\\Documents\\truckProRepo\\truckPRO_api\\deploy.bat"
        # Clean up by removing the key file
        del key
