name: Deploy to Windows VPS

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SSH Commands on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m            
          script: |
                    C:\Users\Administrator\Documents\truckProRepo\truckPRO_api\deploy.bat
  
                    # Check if the bat file ran successfully
  check:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Check if the bat file ran successfully
      if: ${{ needs.ssh.outputs.exitcode == 0 }}
      run: |
          echo "Check if the bat file ran successfully"
