name: Test SSH Connection and Deployment

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test SSH Connection on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "SSH Connection Established!"
            echo "Running test script on VPS..."
            C:\Users\Administrator\Documents\test
