name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest  # Using a Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0

      - name: Run deploy script
        shell: pwsh  
        run: |
          ssh -o StrictHostKeyChecking=no user@174.138.184.240 "C:\\Users\\Administrator\\Documents\\truckProRepo\\truckPRO_api\\deploy"
